"""Audit and controlled-import CLI for external strategy article corpora.

Examples (PowerShell):

    python scripts/strategy_corpus.py audit C:\\path\\to\\corpus --out data\\cache\\corpus-audit
    python scripts/strategy_corpus.py import data\\cache\\corpus-audit\\audit.json C:\\path\\to\\corpus --confirm-unverified

The audit command reads only text and never imports or executes corpus code.
The import command writes prose only to AlphaScope's isolated low-trust RAG
collection and requires an explicit confirmation when the licence is unknown.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Running ``python scripts/strategy_corpus.py`` makes ``scripts/`` the first
# import location.  Add the repository root so the installed package is not a
# prerequisite for this local maintenance utility.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.rag.external_corpus import (
    audit_corpus,
    import_audited_corpus,
    load_audit,
    remove_import_batch,
    write_audit_outputs,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Safe external strategy corpus audit and import")
    subparsers = parser.add_subparsers(dest="command", required=True)

    audit = subparsers.add_parser("audit", help="Create a static audit manifest")
    audit.add_argument("root", type=Path, help="Corpus root containing articles/*/content.md")
    audit.add_argument("--out", type=Path, required=True, help="Directory for audit.json and audit.md")
    audit.add_argument("--repository-url", default="", help="Optional canonical repository URL")

    importer = subparsers.add_parser("import", help="Import audited prose into the isolated RAG collection")
    importer.add_argument("audit", type=Path, help="audit.json generated by the audit command")
    importer.add_argument("root", type=Path, help="The same corpus root used by the audit")
    importer.add_argument(
        "--confirm-unverified",
        action="store_true",
        help="Required when the manifest has no declared license",
    )
    importer.add_argument("--article", action="append", default=[], help="Import only this article id; repeatable")

    remove = subparsers.add_parser("remove", help="Remove a controlled-import batch")
    remove.add_argument("batch_id", help="Batch id returned by the import command")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if args.command == "audit":
        manifest = audit_corpus(args.root, repository_url=args.repository_url or None)
        outputs = write_audit_outputs(manifest, args.out)
        print(json.dumps({"summary": manifest["summary"], "outputs": outputs}, ensure_ascii=False, indent=2))
        return 0
    if args.command == "import":
        manifest = load_audit(args.audit)
        result = import_audited_corpus(
            manifest,
            args.root,
            confirm_unverified=args.confirm_unverified,
            selected_ids=args.article or None,
        )
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0
    if args.command == "remove":
        print(json.dumps(remove_import_batch(args.batch_id), ensure_ascii=False, indent=2))
        return 0
    raise AssertionError(f"Unhandled command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
